### ISSUE TITLE
University-Release Dataset (class 1209)

### ISSUE THREAD

**Issue by Midlij** [layumi/University1652-Baseline#34]
Thank you for providing the University1652 dataset.
I was running the code, but it stopped executing due to not finding any files in the class 1209 under the "/test/gallery_street" folder.
Is the data for class 1209 missing or is it just an issue on end?

**Comment by layumi** [comment]
Hi @Midlij 

Some location does not contain the google street point. So we do not collect any street image. 
Yes. We need to skip such query during test.

**Comment by Midlij** [comment]
Hi @layumi 

I was running this line:
`python '/content/drive/MyDrive/University1652-Baseline-master/train_no_street.py' --name two_view_long_no_street_share_d0.75_256_s1  --share --views 3  --droprate 0.75  --stride 1 --h 256  --w 256  --fp16; `

After that, I get this error:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/University1652-Baseline-master/train_no_street.py", line 385, in <module>
    model = train_model(model, model_test, criterion, optimizer_ft, exp_lr_scheduler,
  File "/content/drive/MyDrive/University1652-Baseline-master/train_no_street.py", line 199, in train_model
    for data,data2,data3,data4 in zip(dataloaders['satellite'], dataloaders['street'], dataloaders['drone'], dataloaders['google']) :
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 229, in __getitem__
    sample = self.loader(path)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 268, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 247, in pil_loader
    img = Image.open(f)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2895, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='./University-Release/train/satellite/1238/1238.jpg'>

```
By the way, I am using Colab if that helps.

**Comment by Midlij** [comment]
Hi @layumi,

I am running train_no_street.py, and I am getting the following error.

```
Traceback (most recent call last):
  File "train_no_street.py", line 364, in <module>
    os.mkdir(dir_name)
FileNotFoundError: [Errno 2] No such file or directory: './model/two_view'

```
Where do I find the "model" folder from?

**Comment by layumi** [comment]
Hi @Midlij 
I guess you only need to mkdir `model` first.
